### ISSUE TITLE
Change the name's gradient

### ISSUE THREAD

**Issue by ednofedulo** [ednofedulo/ednofedulo.github.io#1]
Change the gradient used in the name.

**Comment by vinopaldimit** [comment]
i can do this, but is there a particular gradient you want?

**Comment by ednofedulo** [comment]
no, im bad with design, just want ideas of colors that look good in combination with the background color.

**Comment by vinopaldimit** [comment]
should i send a pull request or just make suggestions here?

**Comment by ednofedulo** [comment]
PR is better
